# Generated by Django 4.0 on 2021-12-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(max_length=300)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd', models.IntegerField()),
                ('plaqueta', models.IntegerField()),
            ],
        ),
    ]
