# Generated by Django 4.0 on 2021-12-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ativo', '0002_categoria_alter_ativo_options_categoriaativos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='categoriaativos',
            options={'ordering': ['categoria', 'ativo']},
        ),
    ]
